# Site settings
title: Active Directory Plugin
email: jijisv@gmail.com
description: "Documentation for Sonar Active Directory Plugin"
baseurl: "http://programmingforliving.github.io/sonar-ad-plugin" 
url: "http://programmingforliving.com" 
exclude: ['.c9', '.git', '.sass-cache']

# Build settings
markdown: kramdown
highlighter: rouge

pflurl: "http://programmingforliving.com"
copyright: "Copyright 2014"

defaults:
  - 
    scope:
      path: ""
    values:
      layout: "page"
